---

- name: Ubuntu Development Environment
  hosts: all
  user: pcoffey
  sudo: false
  vars:
    ansible_ssh_user: pcoffey

  roles:
    - ui
    - dotfiles
    - web
    - php
    - nodejs
    - go
    - mysql
    - drupal
    - frontend
    - linux-dev
    - meteor
    - vm
