---

- name: Paper | Add repository
  apt_repository: repo='ppa:snwh/pulp' state=present update_cache=yes

- name: Paper | Install Paper theme
  apt: name=paper-gtk-theme state=latest

- name: Paper | Install Paper theme icons
  apt: name=paper-icon-theme state=latest
